---
- name: 检查docker是否已安装
  stat:
    path: /root/.state/dockerok
  register: dockerok_result
  no_log: true

- name: docker已安装
  debug:
    msg: docker已安装
  when: dockerok_result.stat.exists

- name: 安装docker
  include_tasks: install-docker.yml
  when: not dockerok_result.stat.exists